### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by NoonyaBeeznus** [andreas-glaser/asus-linux-mint#2]
Hi! Linux Mint newbie with an ASUS TUF FX505HM laptop. My fans currently don't work at all and I am trying to keep my laptop from frying itself after I just replaced the SSD. Luckily I have an external fan table that is doing alright so far, but that means I am not getting nearly enough cooling power. Your code looks promising, but I keep getting an error during the installation. 

First, the code pops up with instructions on the Cargo's bin directory. I can find the env file when I go into the directory, but it wouldn't run with the console commands provided. When I copy-pasted the text into the command line, nothing seemed to happen. 

Second, as the install continued, it gets as far as configuring all the files, but gets stuck with this error: 

`failed to run custom build command for `yeslogic-fontconfig-sys v6.0.0`
`

and ultimately leaves me with this (replaced username path for privacy):

`thread 'main' (54925) panicked at /home/[user]/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yeslogic-fontconfig-sys-6.0.0/build.rs:8:48:
  called `Result::unwrap()` on an `Err` value: "\npkg-config exited with status code 1\n> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags fontconfig\n\nThe system library `fontconfig` required by crate `yeslogic-fontconfig-sys` was not found.\nThe file `fontconfig.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.\nThe PKG_CONFIG_PATH environment variable is not set.\n\nHINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `fontconfig.pc`.\n"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

Any advice would be really appreciated. I am new to Linux and would like to learn more, but I can't do that if my computer dies on me (^.^'')

This is a fresh installation of Linux Mint, and I am just getting my bearings.

**Comment by NoonyaBeeznus** [comment]
Oh, I didn't include everything. 
    Linux Mint version and edition 22.2 
    ASUS laptop model   
                                 ASUS TUF FX506HM
    Kernel version 6.14.0-37-generic
    Graphics hardware Intel Corporation TigerLake-H GT1 [UHD Graphics] (rev 01)
                                       NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)
    Service status
                          Unit asusd.service could not be found.
                           Unit supergfxd.service could not be found.

    Installation logs and error messages
I'm not sure how much of the log I need to provide. It got through a lot of the installation. I've copied three above the error through to when it stopped the code (username replaced)

` Compiling serde v1.0.228
   Compiling font-types v0.10.1
   Compiling yeslogic-fontconfig-sys v6.0.0
error: failed to run custom build command for `yeslogic-fontconfig-sys v6.0.0`

Caused by:
  process didn't exit successfully: `/home/[user]/.local/src/asus-linux/asusctl/target/release/build/yeslogic-fontconfig-sys-be9bf8c39bec5226/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RUST_FONTCONFIG_DLOPEN
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr

  thread 'main' (20491) panicked at /home/[user]/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yeslogic-fontconfig-sys-6.0.0/build.rs:8:48:
  called `Result::unwrap()` on an `Err` value: "\npkg-config exited with status code 1\n> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags fontconfig\n\nThe system library `fontconfig` required by crate `yeslogic-fontconfig-sys` was not found.\nThe file `fontconfig.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.\nThe PKG_CONFIG_PATH environment variable is not set.\n\nHINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `fontconfig.pc`.\n"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:176: build] Error 101
[ERROR] Installation failed. You can try running the script again.
[ERROR] Build directory: /home/[user]/.local/src/asus-linux
[ERROR] Check logs above for specific error details.
`

**Comment by NoonyaBeeznus** [comment]
Okay, turns out I needed to install `libfontconfig1-dev` and that got past the first error. 
Now it is giving me 
'ERROR] asusd.service not found. Installation may have failed.
[ERROR] Installation failed. You can try running the script again.
[ERROR] Build directory: /home/[user]/.local/src/asus-linux
[ERROR] Check logs above for specific error details.

On testing the controls, it is able to change the keyboard aura, but it is not able to access the fan-curve setting. It says that only three of the core functions are supported
```
Supported Core Functions:
[
    "xyz.ljones.Platform",
    "xyz.ljones.Backlight",
    "xyz.ljones.Aura",
]
Supported Platform Properties:
[
    ChargeControlEndThreshold,
    ThrottlePolicy,
]

```

It seems like the fans are not able to be accessed

**Comment by andreas-glaser** [comment]
Hi @NoonyaBeeznus — thanks again for the great logs.

I published v22.2.2 which addresses the two installer issues you hit:
- The installer now pulls in the required GUI build dependencies automatically (so the yeslogic-fontconfig-sys / fontconfig.pc error shouldn’t happen).
- rog-control-center is built with X11 support enabled, so it won’t panic on Cinnamon/X11 sessions (still works on Wayland too).

Release notes: https://github.com/andreas-glaser/asus-linux-mint/releases/tag/v22.2.2

Please re-run the installer and then reboot. If fan control still doesn’t show up in `asusctl -s`, that usually means your specific model/firmware doesn’t expose the fan-curve interface via asusctl (so it’s unfortunately not something the installer can fix).

If you paste your `asusctl -s` output and `sudo journalctl -u asusd -n 100`, I can help confirm what’s supported on your laptop.

**Comment by andreas-glaser** [comment]
Closing since v22.2.2 is released; feel free to reply/reopen if anything is still not working.

**Comment by NoonyaBeeznus** [comment]
Hi @andreas-glaser 

The reinstall finished and went well. Thank you for putting those updates in the installer so quickly!

The fan-curves function is still not accessible. I am about at the point where I suspect it will be that the model's interface is incompatible with asusctl. Alas, in a somewhat vain hope, here is the requested information.

I'm not sure why it printed the information 7 times for one query, but I included it all, errors bolded by me. 
I suspect that means that my fan-curves are inaccessible and will need to sit tight with my external fan cooler and wait for a better programmer to get the asusctl function working on this firmware. 


asusctl -s

> Starting version 6.2.0
> Supported Core Functions:
> [
>     "xyz.ljones.Aura",
>     "xyz.ljones.Backlight",
>     "xyz.ljones.Platform",
> ]
> Supported Platform Properties:
> [
>     ChargeControlEndThreshold,
>     ThrottlePolicy,
> ]
> Supported Keyboard Brightness:
> [
>     Off,
>     Low,
>     Med,
>     High,
> ]
> Supported Aura Modes:
> [
>     Static,
>     Breathe,
>     RainbowCycle,
>     RainbowWave,
>     Pulse,
> ]
> Supported Aura Zones:
> []
> Supported Aura Power Zones:
> [
>     Keyboard,
> ]
> 
> 
> 
> 


journalctl 

> Dec 18 19:34:46 BossBitch asusd[1214]: [INFO  zbus::object_server] dispatch_cal>
> Dec 18 19:34:46 BossBitch asusd[1214]: [INFO  zbus::object_server] dispatch_cal>
> Dec 18 19:40:50 BossBitch asusd[1214]: [DEBUG asusd] Doing on_prepare_for_shutd>
> Dec 18 19:40:50 BossBitch asusd[1214]: [INFO  asusd::ctrl_platform] RogPlatform>
> -- Boot 361fe34f16264916b1bc3b907984f8d1 --
> Dec 18 19:49:17 BossBitch systemd[1]: Starting asusd.service - ASUS Notebook Co>
> Dec 18 19:49:18 BossBitch asusd[24484]: Starting asusd daemon...
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]        daemon v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-anime v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-slash v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]      rog-aura v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]  rog-profiles v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] rog-platform v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Product family: ASUS TUF >
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Board name: FX506HM
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  config_traits] Parsed RON for "a>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found a bat>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Checking ba>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found batte>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found mains>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found USB-C>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] attribute on zbus initial>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_fancurves] Device ha>
> Dec 18 19:49:18 BossBitch asusd[24484]: [ERROR asusd] FanCurves: Profile error:>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Backlig>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Found p>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_backlight] Found pri>
>  ESCOC
> [INFO  asusd]     rog-slash v6.2.0
> [INFO  asusd]      rog-aura v6.2.0
> [INFO  asusd]  rog-profiles v6.2.0
> [INFO  asusd] rog-platform v6.2.0
> [INFO  asusd] Product family: ASUS TUF Gaming F15
> [INFO  asusd] Board name: FX506HM
> [INFO  config_traits] Parsed RON for "asusd::config::Config"
> [INFO  rog_platform::platform] Found platform support at "asus-nb-wmi"
> [INFO  rog_platform::power] Power: Checking "/sys/devices/LNXSYSTM:00/LNXSYBUS:>
> [INFO  rog_platform::power] Found a battery
> [INFO  rog_platform::power] Checking battery attributes
> [INFO  rog_platform::power] Found battery power at "BAT1", matched charge_contr>
> [INFO  rog_platform::power] Power: Checking "/sys/devices/platform/ACPI0003:00/>
> [INFO  rog_platform::power] Found mains power at "ACAD"
> [INFO  rog_platform::power] Power: Checking "/sys/devices/platform/USBC000:00/p>
> [INFO  rog_platform::power] Found USB-C power at "ucsi-source-psy-USBC000:001"
> [INFO  asusd] attribute on zbus initialized
> [INFO  rog_platform::platform] Found platform support at "asus-nb-wmi"
> [INFO  asusd::ctrl_fancurves] Device has profile control available
**> [ERROR asusd] FanCurves: Profile error: Not supported**
> [INFO  rog_platform::backlight] Backlight: Checking "/sys/devices/pci0000:00/00>
> [INFO  rog_platform::backlight] Found primary backlight at "intel_backlight"
> [INFO  asusd::ctrl_backlight] Found primary display backlight
>  ESCOD
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-slash v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]      rog-aura v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]  rog-profiles v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] rog-platform v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Product family: ASUS TUF >
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Board name: FX506HM
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  config_traits] Parsed RON for "a>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found a bat>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Checking ba>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found batte>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found mains>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found USB-C>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] attribute on zbus initial>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_fancurves] Device ha>
> Dec 18 19:49:18 BossBitch asusd[24484]: [ERROR asusd] FanCurves: Profile error:>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Backlig>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Found p>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_backlight] Found pri>
>  ESCOD
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-slash v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]      rog-aura v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]  rog-profiles v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] rog-platform v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Product family: ASUS TUF >
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Board name: FX506HM
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  config_traits] Parsed RON for "a>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found a bat>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Checking ba>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found batte>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found mains>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found USB-C>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] attribute on zbus initial>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_fancurves] Device ha>
**> Dec 18 19:49:18 BossBitch asusd[24484]: [ERROR asusd] FanCurves: Profile error:>**
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Backlig>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Found p>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_backlight] Found pri>
>  ESCOD
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-slash v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]      rog-aura v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]  rog-profiles v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] rog-platform v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Product family: ASUS TUF >
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Board name: FX506HM
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  config_traits] Parsed RON for "a>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found a bat>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Checking ba>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found batte>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found mains>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found USB-C>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] attribute on zbus initial>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_fancurves] Device ha>
**> Dec 18 19:49:18 BossBitch asusd[24484]: [ERROR asusd] FanCurves: Profile error:>**
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Backlig>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Found p>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_backlight] Found pri>
>  ESCOD
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-slash v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]      rog-aura v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]  rog-profiles v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] rog-platform v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Product family: ASUS TUF >
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Board name: FX506HM
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  config_traits] Parsed RON for "a>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found a bat>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Checking ba>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found batte>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found mains>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found USB-C>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] attribute on zbus initial>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_fancurves] Device ha>
**> Dec 18 19:49:18 BossBitch asusd[24484]: [ERROR asusd] FanCurves: Profile error:>**
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Backlig>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Found p>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_backlight] Found pri>
>  ESCOD
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-slash v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]      rog-aura v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]  rog-profiles v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] rog-platform v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Product family: ASUS TUF >
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Board name: FX506HM
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  config_traits] Parsed RON for "a>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found a bat>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Checking ba>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found batte>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found mains>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found USB-C>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] attribute on zbus initial>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_fancurves] Device ha>
**> Dec 18 19:49:18 BossBitch asusd[24484]: [ERROR asusd] FanCurves: Profile error:>**
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Backlig>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Found p>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_backlight] Found pri>
>  ESCOD
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-slash v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]      rog-aura v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]  rog-profiles v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] rog-platform v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Product family: ASUS TUF >
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Board name: FX506HM
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  config_traits] Parsed RON for "a>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found a bat>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Checking ba>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found batte>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found mains>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found USB-C>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] attribute on zbus initial>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_fancurves] Device ha>
> Dec 18 19:49:18 BossBitch asusd[24484]: [ERROR asusd] FanCurves: Profile error:>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Backlig>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Found p>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_backlight] Found pri>
>  ESCOD
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-anime v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]     rog-slash v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]      rog-aura v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd]  rog-profiles v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] rog-platform v6.2.0
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Product family: ASUS TUF >
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] Board name: FX506HM
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  config_traits] Parsed RON for "a>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found a bat>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Checking ba>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found batte>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found mains>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Power: Chec>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::power] Found USB-C>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd] attribute on zbus initial>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::platform] Found pl>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  asusd::ctrl_fancurves] Device ha>
**> Dec 18 19:49:18 BossBitch asusd[24484]: [ERROR asusd] FanCurves: Profile error:>**
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Backlig>
> Dec 18 19:49:18 BossBitch asusd[24484]: [INFO  rog_platform::backlight] Found p>
> lines 9-31
>

**Comment by andreas-glaser** [comment]
I'm happy to help but I don't think there is anything I can do here. 
You best contact the legends at https://asus-linux.org/

I'm really just trying to make their tools work for Mint.

**Comment by barneysspeedshop** [comment]
I just want to say thank you @andreas-glaser for your hard work here
